issue #6062 resolved  - Successful message in account detail & addresses
nopSolutions/nopCommerce pull request #6231
Opened 2022-04-16 16:44 UTC by hosein-habibiyan

PR to close #6062

2022-04-18 08:23 UTC, RomanovM requested changes
@HoseinHabibiyan  There are unwanted changes in [defaultResources.nopres.xml](https://github.com/nopSolutions/nopCommerce/pull/6231/files#diff-a1af1655b1f2658635d918ca78a9acede9b4654549240968a8a3fe8b556e340b) (with line endings I suppose), so all this file was overwritten. Could you fix this, please? 
Also, a new locale should be added to [LocalizationMigration](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web.Framework/Migrations/UpgradeTo460/LocalizationMigration.cs).

2022-04-18 17:23 UTC, HoseinHabibiyan commented
> @HoseinHabibiyan There are unwanted changes in [defaultResources.nopres.xml](https://github.com/nopSolutions/nopCommerce/pull/6231/files#diff-a1af1655b1f2658635d918ca78a9acede9b4654549240968a8a3fe8b556e340b) (with line endings I suppose), so all this file was overwritten. Could you fix this, please? Also, a new locale should be added to [LocalizationMigration](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web.Framework/Migrations/UpgradeTo460/LocalizationMigration.cs).

yes sure . fixed that.
added locale to LocalizationMigration .

2022-04-19 12:03 UTC, RomanovM approved these changes

2022-04-19 12:05 UTC, merged

2022-04-19 12:05 UTC, RomanovM commented
@HoseinHabibiyan Thanks for your help.